<form class="form-horizontal" method="post" action="/user/update">
    <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>">
    <p>Enter your personal data.</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="firstname">First name(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="firstname" placeholder="Enter your first name" name="firstname" required value="<?php echo $this->user['firstname']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="lastname">Last name(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="lastname" placeholder="Enter your last name" name="lastname" required value="<?php echo $this->user['lastname']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="website">Your personal Web page:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="website" placeholder="Enter your personal Web page" name="persional_website" value="<?php echo $this->user['persional_website']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="organization">Organization(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="organization" placeholder="Enter your organization" name="organization" required value="<?php echo $this->user['organization']; ?>">
        </div>
    </div>

    <hr>
    <p>Enter your address.</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="phone">Phone:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="phone" placeholder="Enter your phone" name="phone" value="<?php echo $this->user['phone']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="address">Address, line 1 (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="address" placeholder="Enter your address" name="address" required value="<?php echo $this->user['address']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="address2">Address, line 2:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="address2" placeholder="Enter your address" name="address_2" value="<?php echo $this->user['address_2']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="city">City (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="city" placeholder="Enter your city" name="city" required value="<?php echo $this->user['city']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="postcode">Post code (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="postcode" placeholder="Enter your city" name="postcode" required value="<?php echo $this->user['postcode']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="country">Country (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="country" placeholder="Enter your country" name="country" required value="<?php echo $this->user['country']; ?>">
        </div>
    </div>

    <hr>
    <p>Enter your account information. Note that user names are case-insensitive</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="email">Email (*):</label>
        <div class="col-sm-9">
            <input type="email" class="form-control" id="email" placeholder="Enter your email" name="email" required value="<?php echo $this->user['email']; ?>">
        </div>
    </div>
    <hr>
    <p>Reset your password</p>
    <div class="form-group">
        <div class="checkbox">
            <label><input type="checkbox" name="reset_password" value="1"> Reset password</label>
        </div>
    </div>
    <div class="form-group"> 
        <div class="col-sm-12">
            <button type="submit" class="btn btn-success center-block">UPDATE MY ACCOUNT</button>
        </div>
    </div>
</form>

<?php
echo $this->partial("layout/modal_notice.phtml", array('title' => 'Notice',));
?>