<h1>Users</h1>
<div class="row"></div>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $order => $user): ?>
            <tr>
                <td><?php echo $order + 1; ?></td>
                <td><a href="/user/show?id=<?php echo $user['id']; ?>"><?php echo $user['firstname'] . ' ' . $user['lastname']; ?></a></td>
                <td><a href="mailto:<?php echo $user['email'] ?>"><?php echo $user['email'] ?></a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>