<div class="error-notifice">
    <?php foreach ($this->errors as $error): ?>
        <p>*<?php echo $error; ?></p>
    <?php endforeach; ?>
</div>
<form class="form-horizontal" action="/user/login" method="post">
    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email:</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" placeholder="Enter email" required name="email">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Password:</label>
        <div class="col-sm-10"> 
            <input type="password" class="form-control" id="pwd" placeholder="Enter password" required name="password">
        </div>
    </div>
    <!-- <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2"> 
            <a href="/user/signup">Create an account</a>
        </div>
    </div> -->
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2"> 
            <a href="/user/forgot">Forgot your password?</a>
        </div>
    </div>
    <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
    </div>
</form>
