<form class="form-horizontal signup" method="post" action="/user/create">
    <p>To use RC-EnvE2017, you must agree to its Terms of Service (<a href="#">view terms</a>), (<a href="">download terms</a>)</p>
    <div class="form-group"> 
        <div class="col-sm-12">
            <div class="checkbox">
                <label><input type="checkbox" class="agree"> I agree to RC-EnvE2017 Terms of Service</label>
            </div>
        </div>
    </div>
    <hr>
    <p>Enter your personal data.</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="firstname">First name(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="firstname" placeholder="Enter your first name" name="firstname" required>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="lastname">Last name(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="lastname" placeholder="Enter your last name" name="lastname" required>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="website">Your personal Web page:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="website" placeholder="Enter your personal Web page" name="persional_website">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="organization">Organization(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="organization" placeholder="Enter your organization" name="organization" required>
        </div>
    </div>

    <hr>
    <p>Enter your address.</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="phone">Phone:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="phone" placeholder="Enter your phone" name="phone">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="address">Address, line 1 (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="address" placeholder="Enter your address" name="address" required>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="address2">Address, line 2:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="address2" placeholder="Enter your address" name="address_2">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="city">City (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="city" placeholder="Enter your city" name="city" required>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="postcode">Post code (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="postcode" placeholder="Enter your city" name="postcode" required>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="country">Country (*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="country" placeholder="Enter your country" name="country" required>
        </div>
    </div>

    <hr>
    <p>Enter your account information. Note that user names are case-insensitive</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="email">Email (*):</label>
        <div class="col-sm-9">
            <input type="email" class="form-control" id="email" placeholder="Enter your email" name="email" required>
        </div>
    </div>

    <div class="form-group"> 
        <div class="col-sm-12">
            <button type="submit" class="btn btn-success center-block signup">CREATE MY ACCOUNT</button>
        </div>
    </div>
</form>

<?php
echo $this->partial("layout/modal_notice.phtml", array('title' => 'Notice',));
?>