<h1>
    <?php echo $this->category['name']; ?>
</h1>
<div class="row"></div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Category</th>
            <th>Author</th>
            <th>Created</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $order = 1;
        foreach ($this->newspapers as $news):
            ?>
            <tr id="news-<?php echo $news['id']; ?>">
                <td><?php echo $order++; ?></td>
                <td class="id"><?php echo $news['id']; ?></td>
                <td class="name title"><a href="/news/show?id=<?php echo $news['id']; ?>"><?php echo $news['title']; ?></a><?php if ($news['type'] == 1) : ?> <span style="color: red;">(Hot)</span><?php endif; ?></td>
                <td class="category"><a href="/category/show?id=<?php echo $news['category_id'] ?>"><?php echo $news['category']; ?></a></td>
                <td class="user"><?php echo $news['firstname'] . ' ' . $news['lastname']; ?></td>
                <td class="created"><?php echo $news['created_at']; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

